### PR TITLE
Remove VTI Theme (New design)

### PR DESCRIPTION
**Pull request by fairbird**
After last commit 
https://github.com/PLi-metas/pli-extras/commit/0f0f068e9f674577cebdcde84082f85316ce943c#diff-147e5a8e0a6ca7a34b73f60ac3f1a1f7
Plugin after compiled comes 10MB 

So this commit delete New design and save 5MB free space in flash To devices have small flash such as dm800, 800se ..etc

### CODE REVIEW

**Comment by Hains** [comment]
Can you make this with a 'bb.utils.contains' and use 'small flash' as MACHINE_FEATURE.
I'm not getting happy from remove this today, and tomorrow that, unconditionally until there's nothing left.
Just for a few boxes.

**Comment by fairbird** [comment]
Is this  code correct ?!

> do_compile() {
### Remove VTI Theme to smallflash devices
        ${@bb.utils.contains("MACHINE_FEATURES", "smallflash", " \
	rm -rf ${S}/plugin/controllers/views/responsive >/dev/null 2>&1 || true
	rm -rf ${S}/plugin/public/themes/absb >/dev/null 2>&1 || true
	rm -rf ${S}/plugin/public/css/vti* >/dev/null 2>&1 || true
	rm -rf ${S}/plugin/public/js/vti* >/dev/null 2>&1 || true
	rm -rf ${S}/plugin/public/js/openwebif-1.2.14.min.js >/dev/null 2>&1 || true
	rm -rf ${S}/plugin/public/js/openwebif-1.2.10.min.js >/dev/null 2>&1 || true
	rm -rf ${S}/plugin/public/js/chosen.jquery.min.js >/dev/null 2>&1 || true
	rm -rf ${S}/plugin/public/static/remotes >/dev/null 2>&1 || true
        "
### END
	cheetah-compile -R --nobackup ${S}/plugin
	python -O -m compileall ${S}
}

**Comment by Hains** [comment]
I can't test at the moment, but your missing :
```
"", d
```
at the end at least.

**Comment by fairbird** [comment]
Ok.. I will Test it.
And if success I will make new commit ..

**Comment by Hains** [comment]
Try this:
```
${@bb.utils.contains("MACHINE_FEATURES", "smallflash", " \
rm -rf ${S}/plugin/controllers/views/responsive >/dev/null 2>&1 || true \
rm -rf ${S}/plugin/public/themes/absb >/dev/null 2>&1 || true \
rm -rf ${S}/plugin/public/css/vti* >/dev/null 2>&1 || true \
rm -rf ${S}/plugin/public/js/vti* >/dev/null 2>&1 || true \
rm -rf ${S}/plugin/public/js/openwebif-1.2.14.min.js >/dev/null 2>&1 || true \
rm -rf ${S}/plugin/public/js/openwebif-1.2.10.min.js >/dev/null 2>&1 || true \
rm -rf ${S}/plugin/public/js/chosen.jquery.min.js >/dev/null 2>&1 || true \
rm -rf ${S}/plugin/public/static/remotes >/dev/null 2>&1 || true \
    ", "" ,d )}

**Comment by Hains** [comment]
BTW, are you sure you need to delete 'plugin/public/static/remotes '.
There is cleanup mechanism in bbappend. See line 179-193.
And do you still have image of your box, remote control etc?

**Comment by fairbird** [comment]
no it is My fault

**Comment by Hains** [comment]
New PR.

**Pull request closed without merging**
