### PR TITLE
fix bitstream recipe

### PR DESCRIPTION
**Pull request by moham96**

### CODE REVIEW

**Comment by Hains** [comment]
See:
https://github.com/OpenPLi/openpli-oe-core/commit/3fde7c378142341e3a5ebc28ecb982ffcd3055ee

So that makes the bbappend superflous

**Comment by moham96** [comment]
@Hains  It fails to build for me because it downloads the URL as an HTML page , I had to change the it to the above to get it to build.
see my comment here https://forums.openpli.org/topic/57878-howto-build-unofficial-pli-for-your-unsupported-receiver/?view=findpost&p=903898

**Comment by moham96** [comment]
another problem that I didn't fix in the pull request is that the bb recipe doesn't contain a version number so the ${SRCPV} is not expanded which result in the working folder being created like so:
build/tmp/work/aarch64-oe-linux/bitstream/1.0+git${SRCPV}-r0

**Comment by persianpros** [comment]
Best thing is mirror it here on PLi-metas's github.

**Comment by Hains** [comment]
+1.
Videolan is often down.

**Pull request closed without merging**
